### ISSUE TITLE
It shows only upto 2 levels

### ISSUE THREAD

**Issue by ramkiit36** [yianni-ververis/google-organizational-chart#1]
I added 3 dimensions, even though showing upto 2 levels.

![capture](https://cloud.githubusercontent.com/assets/28921918/26399123/617a3838-4099-11e7-9be8-54df067e9006.JPG)

**Comment by yianni-ververis** [comment]
Please update. I just took a screenshot from the attached qvf n June 17 release and I have up to 4 levels
